pschanely/CrossHair

- crosshair/objectproxy.py
__import [operator](https://docs.python.org/3/library/operator.html)__ to avoid raising NameError at runtime.
> Undefined name: import operator

- .travis.yml
- crosshair/abcstring.py
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int …
> Lint Python code for syntax errors and undefined names

- crosshair/main.py
`report_all` is only an attribute of argparse namespace when running
check not watch, so when running watch just set that to false
Closes #24
> Fixes running watch command

- crosshair/__main__.py
- crosshair/main.py
This patch allows CrossHair to be run as a module, *i.e.*,
`python -m crosshair ...`. This is necessary for the environments which
depend on Python interpreter (*e.g.*, IDEs in Windows).
> Run CrossHair as module

- crosshair/util_test.py
The previous threshold for opcode coverage was set to 0.9. However, on
my Windows machine, the coverage is 0.88.
This patch lowers the threshold arbitrarily to 0.85.
> Fix expected coverage in `util_test`

- .travis.yml
- README.md
- crosshair/examples/icontract/bugs_detected/showcase.py
- doc/contributing.md
- precommit.py
- setup.py
This patch introduces a commit script to run one, more or all pre-commit
checks from the command line or as part of our continuous integration
pipeline.
It also documents the contributing guidelines, which also explain how to
set up the development environment.
> Add precommit script

- precommit.py
This patch adds a comment explaining why we run doctests in a separate
step in the precommit script. This is necessary in order to avoid
confusion as it is actually possible to execute doctests during testing.
See also [this comment on the pull request #71][comment].
[comment]: https://github.com/pschanely/CrossHair/pull/71#discussion_r570356585
> Comment why doctest on doc separate in precommit

- .github/workflows/publish-to-pypi.yml
- setup.py
This patch introduces a GitHub workflow that is triggered on a GitHub
release. The workflow automatically builds the source distribution and
uploads it to PyPI.
> Publish continuously to PyPI

- additional-verbs-in-imperative-mood.txt
- check_init_and_setup_coincide.py
- crosshair/__init__.py
- precommit.py
- setup.py
We need to denormalize the medata (such as version, author, license
*etc.*) between `setup.py` and `crosshair/__init__.py` so that both
Sphinx and setup can access them.
Mind that you can not import the module (`crosshair/__init__.py`) from
within `setup.py` as this would cause race condition during the
installation.
To enforce the consistency, we add a script to the pre-commit checks.
> Undry metadata from setup.py

- crosshair/core_test.py
We omitted to reformat the file `core_test.py` by mistake.
> Reformat `core_test.py`

- doc/source/changelog.rst
- doc/source/contributing.rst
- doc/source/related_work.rst
- doc/source/why_should_i_use_crosshair.rst
This patch makes various minor fixes to the documentation. Namely, the
external links with the named target were lacking the suffix underscore
("_"), and certain code blocks were missing double colon suffix 
(`..code-block:` instead of `.. code-block::`).
> Fix links and code blocks in the doc

- check_help_in_doc.py
- doc/source/command-line_interface.rst
- doc/source/contributing.rst
- doc/source/index.rst
- precommit.py
This patch documents the command-line interface in the documentation.
To ensure that the documentation is always up-to-date, the patch also
includes a script that verifies the output of `--help` against the
documentation.
> Document command-line interface

- doc/source/how_does_it_work.rst
- precommit.py
The `precommit.py` was checking on `*.md` documents in the `doc/`
directory, but the documentation was translated to RST + Sphinx in the
pull request #79.
> Fix doctesting for doc

- crosshair/util.py
It can happen that `filename` is not defined when
returning from `sourcelines`. The `or` clause does
not fire in this case, instead a `NameError` is raised.
This PR fixes that and ensures `<unknown filename>`
is returned instead. This makes it possible to use
`analyze_function` in an interactive session.
> Fix `sourcelines`

- additional-verbs-in-imperative-mood.txt
- crosshair/core.py
- crosshair/libimpl/builtinslib.py
- crosshair/libimpl/builtinslib_ch_test.py
- crosshair/libimpl/builtinslib_test.py
- crosshair/test_util.py
@Rik-de-Kort Spent a little time thinking about testing recently, and took some [notes here](https://github.com/pschanely/CrossHair/discussions/97).
I've been trying to figure out how to efficiently test all these tricky edge cases, and I think the approach in `builtinslib_ch_test.py` is reasonably effective (though I suspect still insufficient). I've left a variety of cases commented that aren't quite passing yet.
I also did some refactoring of `rfind` here: partly to cover some more of those edge cases, but also to try and get around some of the z3 unknown results we've been seeing. I have a suspicion that the string solver doesn't love to reason about numeric indices: it's possible that doing so requires the linear arithmetic solver to cooperate with the string solver, and things get …
> Add self-tests for string methods

- crosshair/condition_parser.py
- crosshair/core_and_libs.py
- crosshair/core_test.py
- doc/source/contributing.rst
Seamless handoff between symbolic and concrete tooling 🤩
> Save Hypothesis buffer to database

- crosshair/path_cover.py
- crosshair/path_cover_test.py
- doc/source/contributing.rst
This is suggested solution to  #217
> Add assertion message handling in pytest cover command

- .pre-commit-config.yaml
- crosshair/libimpl/builtinslib.py
- crosshair/libimpl/builtinslib_test.py
- crosshair/patch_equivalence_test.py
- crosshair/simplestructs.py
- crosshair/simplestructs_test.py
- crosshair/tracers.py
- doc/source/contributing.rst
Wraps plain `set()` and `dict()` constructors in object that can detect later symbolic additions and avoid realizing them.
> Avoid hashing when adding symbolic to a concrete set or dict

- crosshair/diff_behavior.py
- crosshair/diff_behavior_test.py
- crosshair/fuzz_core_test.py
- crosshair/test_util.py
- crosshair/test_util_test.py
> Loosen diff behavior equality comparisons

- doc/source/contracts.rst
- doc/source/contributing.rst
Hey, thanks for this really cool library. I skipped creating an issue since it's such a small change.
Fix minor typos in the docs - the "crosshair" keyword is outside of the example code block.
> Update contracts.rst (fix typos)
